import "./raw-output";
import "./validation";
import "./json-tree";
import "./json-diagram";
import "./table";
import "./diff";
import "./visual-diff";
import "./image-split";
import "./image-fade";
import "./image-slider";
import "./image-highlight";
import "./image-details";
import "./mermaid";
import "./counter";
import "./code-image";
import "./port-viewer";
import "./duplicate-viewer";
import "./port-table";
// import "./image-canvas-fabric";
import "./image-canvas-excalidraw";
// import "./image-canvas-tldraw";

export { getOutputViewsForTransform, registerOutputView } from "./registry";
export type { OutputViewConfig } from "./registry";
