import type { Monaco } from "@monaco-editor/react";
import type { editor } from "monaco-editor";

export function defineMonacoThemes(monaco: Monaco) {
  // Catppuccin Mocha
  monaco.editor.defineTheme("typa-dark", {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6c7086", fontStyle: "italic" },
      { token: "keyword", foreground: "cba6f7" },
      { token: "keyword.control", foreground: "cba6f7" },
      { token: "storage", foreground: "cba6f7" },
      { token: "storage.type", foreground: "f9e2af" },
      { token: "string", foreground: "a6e3a1" },
      { token: "string.escape", foreground: "f2cdcd" },
      { token: "number", foreground: "fab387" },
      { token: "constant", foreground: "fab387" },
      { token: "variable", foreground: "cdd6f4" },
      { token: "variable.parameter", foreground: "f2cdcd" },
      { token: "type", foreground: "f9e2af" },
      { token: "type.identifier", foreground: "f9e2af" },
      { token: "entity.name.function", foreground: "89b4fa" },
      { token: "entity.name.type", foreground: "f9e2af" },
      { token: "support.function", foreground: "89b4fa" },
      { token: "function", foreground: "89b4fa" },
      { token: "method", foreground: "89b4fa" },
      { token: "operator", foreground: "89dceb" },
      { token: "tag", foreground: "cba6f7" },
      { token: "attribute.name", foreground: "f9e2af" },
      { token: "attribute.value", foreground: "a6e3a1" },
      { token: "delimiter", foreground: "9399b2" },
      { token: "delimiter.bracket", foreground: "9399b2" },
      { token: "punctuation", foreground: "9399b2" },
      { token: "meta.embedded", foreground: "cdd6f4" },
      { token: "regexp", foreground: "f5c2e7" },
      { token: "annotation", foreground: "f5c2e7" },
      { token: "identifier", foreground: "cdd6f4" },
    ],
    colors: {
      "editor.background": "#1e1e2e",
      "editor.foreground": "#cdd6f4",
      "editorLineNumber.foreground": "#45475a",
      "editorLineNumber.activeForeground": "#a6adc8",
      "editor.lineHighlightBackground": "#2a2b3d",
      "editor.selectionBackground": "#45475a80",
      "editor.inactiveSelectionBackground": "#45475a40",
      "editorCursor.foreground": "#f5e0dc",
      "editorGutter.background": "#1e1e2e",
      "editorWidget.background": "#313244",
      "editorWidget.border": "#45475a",
      "editorIndentGuide.background": "#31324450",
      "editorBracketMatch.background": "#45475a50",
      "editorBracketMatch.border": "#cba6f750",
      "editor.findMatchBackground": "#f9e2af30",
      "editor.findMatchHighlightBackground": "#f9e2af15",
      "editorSuggestWidget.background": "#1e1e2e",
      "editorSuggestWidget.border": "#45475a",
      "editorSuggestWidget.selectedBackground": "#45475a",
      "editorHoverWidget.background": "#1e1e2e",
      "editorHoverWidget.border": "#45475a",
      "input.background": "#313244",
      "input.border": "#45475a",
      "input.foreground": "#cdd6f4",
      "scrollbar.shadow": "#00000000",
      "scrollbarSlider.background": "#45475a60",
      "scrollbarSlider.hoverBackground": "#45475a90",
      "scrollbarSlider.activeBackground": "#45475ab0",
    },
  });

  // Catppuccin Latte
  monaco.editor.defineTheme("typa-light", {
    base: "vs",
    inherit: true,
    rules: [
      { token: "comment", foreground: "9ca0b0", fontStyle: "italic" },
      { token: "keyword", foreground: "8839ef" },
      { token: "keyword.control", foreground: "8839ef" },
      { token: "storage", foreground: "8839ef" },
      { token: "storage.type", foreground: "df8e1d" },
      { token: "string", foreground: "40a02b" },
      { token: "string.escape", foreground: "dd7878" },
      { token: "number", foreground: "fe640b" },
      { token: "constant", foreground: "fe640b" },
      { token: "variable", foreground: "4c4f69" },
      { token: "variable.parameter", foreground: "dd7878" },
      { token: "type", foreground: "df8e1d" },
      { token: "type.identifier", foreground: "df8e1d" },
      { token: "entity.name.function", foreground: "1e66f5" },
      { token: "entity.name.type", foreground: "df8e1d" },
      { token: "support.function", foreground: "1e66f5" },
      { token: "function", foreground: "1e66f5" },
      { token: "method", foreground: "1e66f5" },
      { token: "operator", foreground: "179299" },
      { token: "tag", foreground: "8839ef" },
      { token: "attribute.name", foreground: "df8e1d" },
      { token: "attribute.value", foreground: "40a02b" },
      { token: "delimiter", foreground: "7c7f93" },
      { token: "delimiter.bracket", foreground: "7c7f93" },
      { token: "punctuation", foreground: "7c7f93" },
      { token: "meta.embedded", foreground: "4c4f69" },
      { token: "regexp", foreground: "ea76cb" },
      { token: "annotation", foreground: "ea76cb" },
      { token: "identifier", foreground: "4c4f69" },
    ],
    colors: {
      "editor.background": "#eff1f5",
      "editor.foreground": "#4c4f69",
      "editorLineNumber.foreground": "#bcc0cc",
      "editorLineNumber.activeForeground": "#7c7f93",
      "editor.lineHighlightBackground": "#e6e9ef",
      "editor.selectionBackground": "#acb0be60",
      "editor.inactiveSelectionBackground": "#acb0be30",
      "editorCursor.foreground": "#dc8a78",
      "editorGutter.background": "#eff1f5",
      "editorWidget.background": "#e6e9ef",
      "editorWidget.border": "#ccd0da",
      "editorIndentGuide.background": "#ccd0da50",
      "editorBracketMatch.background": "#acb0be50",
      "editorBracketMatch.border": "#8839ef50",
      "editor.findMatchBackground": "#df8e1d30",
      "editor.findMatchHighlightBackground": "#df8e1d15",
      "editorSuggestWidget.background": "#eff1f5",
      "editorSuggestWidget.border": "#ccd0da",
      "editorSuggestWidget.selectedBackground": "#ccd0da",
      "editorHoverWidget.background": "#eff1f5",
      "editorHoverWidget.border": "#ccd0da",
      "input.background": "#e6e9ef",
      "input.border": "#ccd0da",
      "input.foreground": "#4c4f69",
      "scrollbar.shadow": "#00000000",
      "scrollbarSlider.background": "#acb0be50",
      "scrollbarSlider.hoverBackground": "#acb0be80",
      "scrollbarSlider.activeBackground": "#acb0bea0",
    },
  });
}

export const sharedEditorOptions: editor.IStandaloneEditorConstructionOptions = {
  minimap: { enabled: false },
  fontFamily: "'SF Mono', 'Fira Code', 'JetBrains Mono', ui-monospace, monospace",
  fontWeight: "400",
  letterSpacing: 0.3,
  padding: { top: 12, bottom: 12 },
  lineDecorationsWidth: 12,
  scrollBeyondLastLine: false,
  wordWrap: "on",
  renderLineHighlight: "none",
  occurrencesHighlight: "off",
  selectionHighlight: false,
  overviewRulerLanes: 0,
  hideCursorInOverviewRuler: true,
  overviewRulerBorder: false,
  automaticLayout: true,
  cursorBlinking: "smooth",
  cursorSmoothCaretAnimation: "on",
  smoothScrolling: true,
  tabSize: 2,
  renderWhitespace: "none",
  guides: { indentation: false },
  lineNumbers: "on",
  lineNumbersMinChars: 3,
  glyphMargin: false,
  folding: false,
  scrollbar: {
    vertical: "auto",
    horizontal: "auto",
    verticalScrollbarSize: 6,
    horizontalScrollbarSize: 6,
    useShadows: false,
  },
};
